Tải dữ liệu

In [3]:
# from google.colab import files
# import pandas as pd
# import re

In [ ]:
uploaded = files.upload()

Saving Quy_Che_Quy_Dinh.xlsx to Quy_Che_Quy_Dinh.xlsx
Saving Thong_Tin_Khoa.csv to Thong_Tin_Khoa.csv

In [5]:
import pandas as pd
import re

In [7]:
# df = pd.read_excel('Quy_Che_Quy_Dinh.xlsx')
# df1 = pd.read_excel('Thong_Tin_Trung_Tam.xlsx')
# df2 = pd.read_excel('Thong_Tin_Tuyen_Sinh.xlsx')
# df3 = pd.read_csv('Thong_Tin_Khoa.csv')
# df4 = pd.read_csv('Thong_Tin_Truong.csv')
df = pd.read_csv('data.csv')

#Hàm làm sạch văn bản quy chế quy định

In [12]:
import re

def clean_text(text):

    if not isinstance(text, str):
        return text

    text = text.strip()

    # lowercase
    text = text.lower()

    # replace url
    text = re.sub(r'http[s]?://\S+', '[URL]', text)

    # remove list markers
    text = re.sub(r'^\s*(\d+\.|[IVXLCDM]+\.|[a-zA-Z]\.|[a-zA-Z]\)|[-+–])\s*', '', text)

    # normalize dash
    text = text.replace('–', '-')

    # remove special characters
    text = re.sub(r'[\"“”…<>*&=]', '', text)

    # normalize spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [13]:
df['Cleaned_Text'] = df['Thong_Tin'].apply(clean_text) #làm sạch dữ liệu nhãn Quy_Che_Quy_Dinh
df

,STT,Thong_Tin,Label,Cleaned_Text
0,1,Website chính thức của Trung tâm Quản trị Hệ t...,Thong_Tin_Trung_Tam,website chính thức của trung tâm quản trị hệ t...
1,2,Tên tiếng Anh của Trung tâm Quản trị Hệ thống ...,Thong_Tin_Trung_Tam,tên tiếng anh của trung tâm quản trị hệ thống ...
2,3,Tên viết tắt của Trung tâm Quản trị Hệ thống l...,Thong_Tin_Trung_Tam,tên viết tắt của trung tâm quản trị hệ thống l...
3,4,Trong quá trình xây dựng và phát triển ban đầu...,Thong_Tin_Trung_Tam,trong quá trình xây dựng và phát triển ban đầu...
4,5,"Tháng 8 năm 2019, Trung tâm Quản trị Hệ thống ...",Thong_Tin_Trung_Tam,"tháng 8 năm 2019, trung tâm quản trị hệ thống ..."
...,...,...,...,...
5351,5352,"Hội thi tay nghề Bộ Công thương năm 2014, IUH ...",Thong_Tin_Truong,"hội thi tay nghề bộ công thương năm 2014, iuh ..."
5352,5353,Hoạt động kỷ niệm ngày Quốc tế Phụ nữ 8/3/2014,Thong_Tin_Truong,hoạt động kỷ niệm ngày quốc tế phụ nữ 8/3/2014
5353,5354,Tiến độ đào tạo năm học 2014-2015 (theo 2 học kỳ),Thong_Tin_Truong,tiến độ đào tạo năm học 2014-2015 (theo 2 học kỳ)
5354,5355,Kế hoạch thi tốt nghiệp đợt tháng 07 năm 2014,Thong_Tin_Truong,kế hoạch thi tốt nghiệp đợt tháng 07 năm 2014
5355,5356,Danh sách các nhà tài trợ học bổng Sinh viên n...,Thong_Tin_Truong,danh sách các nhà tài trợ học bổng sinh viên n...

In [ ]:
df1['Cleaned_Text'] = df1['Text'].apply(clean_text) #làm sạch dữ liệu nhãn Thong_Tin_Trung_Tam
df1

,STT,Text,Labels,Cleaned_Text
0,1,Website chính thức của Trung tâm Quản trị Hệ t...,Thong_Tin_Trung_Tam,Website chính thức của Trung tâm Quản trị Hệ t...
1,2,Tên tiếng Anh của Trung tâm Quản trị Hệ thống ...,Thong_Tin_Trung_Tam,Tên tiếng Anh của Trung tâm Quản trị Hệ thống ...
2,3,Tên viết tắt của Trung tâm Quản trị Hệ thống l...,Thong_Tin_Trung_Tam,Tên viết tắt của Trung tâm Quản trị Hệ thống l...
3,4,Trong quá trình xây dựng và phát triển ban đầu...,Thong_Tin_Trung_Tam,Trong quá trình xây dựng và phát triển ban đầu...
4,5,"Tháng 8 năm 2019, Trung tâm Quản trị Hệ thống ...",Thong_Tin_Trung_Tam,"Tháng 8 năm 2019, Trung tâm Quản trị Hệ thống ..."
...,...,...,...,...
1213,1214,"Để phù hợp với môi trường thao trường, hệ thốn...",Thong_Tin_Trung_tam,"Để phù hợp với môi trường thao trường, hệ thốn..."
1214,1215,Thiết bị tính điểm bia bắn do Trung tâm R&DTec...,Thong_Tin_Trung_tam,Thiết bị tính điểm bia bắn do Trung tâm RDTech...
1215,1216,"Dự án ""Hệ thống thông minh tính điểm tự động c...",Thong_Tin_Trung_tam,Dự án Hệ thống thông minh tính điểm tự động ch...
1216,1217,"Về mặt phần cứng, hệ thống của Trung tâm R&DTe...",Thong_Tin_Trung_tam,"Về mặt phần cứng, hệ thống của Trung tâm RDTec..."
1217,1218,Phần mềm hệ thống tính điểm của Trung tâm R&DT...,Thong_Tin_Trung_tam,Phần mềm hệ thống tính điểm của Trung tâm RDTe...

In [64]:
df2['Cleaned_Text'] = df2['Text'].apply(clean_text) #làm sạch dữ liệu nhãn Thong_Tin_Tuyen_Sinh
df2

,STT,Text,Labels,Cleaned_Text
0,1,"Năm 2026, Trường Đại học Công nghiệp Thành phố...",Thong_Tin_Tuyen_Sinh,"Năm 2026, Trường Đại học Công nghiệp Thành phố..."
1,2,Nguyên tắc chung trong công tác tuyển sinh đại...,Thong_Tin_Tuyen_Sinh,Nguyên tắc chung trong công tác tuyển sinh đại...
2,3,Đối tượng tuyển sinh hệ đại học chính quy năm ...,Thong_Tin_Tuyen_Sinh,Đối tượng tuyển sinh hệ đại học chính quy năm ...
3,4,Thí sinh dự tuyển vào Trường Đại học Công nghi...,Thong_Tin_Tuyen_Sinh,Thí sinh dự tuyển vào Trường Đại học Công nghi...
4,5,Phạm vi tuyển sinh đại học hệ chính quy năm 20...,Thong_Tin_Tuyen_Sinh,Phạm vi tuyển sinh đại học hệ chính quy năm 20...
...,...,...,...,...
1081,1082,Trong khoảng thời gian 01 tháng chờ đợi làm th...,Thong_Tin_Tuyen_Sinh,Trong khoảng thời gian 01 tháng chờ đợi làm th...
1082,1083,Học viên cao học tại IUH tốt nghiệp loại xuất ...,Thong_Tin_Tuyen_Sinh,Học viên cao học tại IUH tốt nghiệp loại xuất ...
1083,1084,IUH cho phép học viên thạc sĩ tham gia trao đổ...,Thong_Tin_Tuyen_Sinh,IUH cho phép học viên thạc sĩ tham gia trao đổ...
1084,1085,"Ngoài IELTS và VSTEP, các chứng chỉ ngoại ngữ ...",Thong_Tin_Tuyen_Sinh,"Ngoài IELTS và VSTEP, các chứng chỉ ngoại ngữ ..."
1085,1086,"Trong trường hợp thiên tai, dịch bệnh bất khả ...",Thong_Tin_Tuyen_Sinh,"Trong trường hợp thiên tai, dịch bệnh bất khả ..."

In [65]:
df3['Cleaned_Text'] = df3['Thông tin'].apply(clean_text) #làm sạch dữ liệu nhãn Thong_Tin_Khoa
df3

,STT,Thông tin,Label,Cleaned_Text
0,1,Website của khoa công nghệ cơ khí: fme.iuh.edu.vn,Thong_tin_khoa,Website của khoa công nghệ cơ khí: fme.iuh.edu.vn
1,2,Email của khoa công nghệ cơ khí: fme@iuh.edu.vn,Thong_tin_khoa,Email của khoa công nghệ cơ khí: fme@iuh.edu.vn
2,3,Khoa Công nghệ Cơ khí được thành lập năm 2005....,Thong_tin_khoa,Khoa Công nghệ Cơ khí được thành lập năm 2005....
3,4,Khoa Công nghệ Cơ khí hiện nay đảm nhiệm công ...,Thong_tin_khoa,Khoa Công nghệ Cơ khí hiện nay đảm nhiệm công ...
4,5,Khoa Công nghệ Cơ khí có sáu đơn vị trực thuộc...,Thong_tin_khoa,Khoa Công nghệ Cơ khí có sáu đơn vị trực thuộc...
...,...,...,...,...
1002,1003,Hội thảo khoa học sinh viên 2019,Thong_tin_khoa,Hội thảo khoa học sinh viên 2019
1003,1004,Thông báo về việc mở lớp học phần học lại của ...,Thong_tin_khoa,Thông báo về việc mở lớp học phần học lại của ...
1004,1005,Kế hoạch hội thảo sinh viên năm 2019,Thong_tin_khoa,Kế hoạch hội thảo sinh viên năm 2019
1005,1006,Chương trình ngày hội tư vấn và thay nhớt miễn...,Thong_tin_khoa,Chương trình ngày hội tư vấn và thay nhớt miễn...
1006,1007,Thông báo danh sách dự kiến sinh viên nhận học...,Thong_tin_khoa,Thông báo danh sách dự kiến sinh viên nhận học...

In [66]:
df4['Cleaned_Text'] = df4['Content'].apply(clean_text) #làm sạch dữ liệu nhãn Thong_Tin_Truong
df4

,STT,Content,Label,Cleaned_Text
0,1,Chúc mừng Giáng sinh và Chúc mừng năm mới 2026,Thong_Tin_Truong,Chúc mừng Giáng sinh và Chúc mừng năm mới 2026
1,2,Hội Cựu chiến binh IUH về nguồn kỷ niệm 81 năm...,Thong_Tin_Truong,Hội Cựu chiến binh IUH về nguồn kỷ niệm 81 năm...
2,3,Đại biểu IUH trúng cử vào Ban Thường vụ Công đ...,Thong_Tin_Truong,Đại biểu IUH trúng cử vào Ban Thường vụ Công đ...
3,4,Biến vảy cá thành giá trị xanh: Sinh viên IUH ...,Thong_Tin_Truong,Biến vảy cá thành giá trị xanh: Sinh viên IUH ...
4,5,"Vượt qua hơn 140 đội thi, sinh viên IUH giành ...",Thong_Tin_Truong,"Vượt qua hơn 140 đội thi, sinh viên IUH giành ..."
...,...,...,...,...
523,524,Bế mạc Hội thao toàn trường năm 2014: Trao 99 ...,Thong_Tin_Truong,Bế mạc Hội thao toàn trường năm 2014: Trao 99 ...
524,525,Trường Đại học Công nghiệp TP. HCM tổ chức Hội...,Thong_Tin_Truong,Trường Đại học Công nghiệp TP. HCM tổ chức Hội...
525,526,Kỷ niệm 9 năm ngày thành lập Trường Đại học Cô...,Thong_Tin_Truong,Kỷ niệm 9 năm ngày thành lập Trường Đại học Cô...
526,527,Hội nghị tổng kết hoạt động công đoàn năm học ...,Thong_Tin_Truong,Hội nghị tổng kết hoạt động công đoàn năm học ...
527,528,GIỚI THIỆU ĐẠI HỌC CÔNG NGHIỆP THÀNH PHỐ HỒ CH...,Thong_Tin_Truong,GIỚI THIỆU ĐẠI HỌC CÔNG NGHIỆP THÀNH PHỐ HỒ CH...

In [ ]:
df.to_csv('Quy_Che_Quy_Dinh_Cleaned.csv', index=False, encoding='utf-8-sig')
# df1.to_csv('Thong_Tin_Trung_Tam_Cleaned.csv', index=False, encoding='utf-8-sig')
# df2.to_csv('Thong_Tin_Tuyen_Sinh_Cleaned.csv', index=False, encoding='utf-8-sig')
# df3.to_csv('Thong_Tin_Khoa_Cleaned.csv', index=False, encoding='utf-8-sig')
# df4.to_csv('Thong_Tin_Truong_Cleaned.csv', index=False, encoding='utf-8-sig')

NameError: name 'df1' is not defined

In [16]:
df.to_csv('data_clean.csv', index=False, encoding='utf-8-sig')